"""Generalised belief propagation on the clustered neighbourhoods of real networks.

``gbp_cliques.py`` asked what the region-graph repair buys on hyperbolic random
graphs, where clustering comes from an underlying geometry.  It found GBP exact
on chordal instances, two to nine orders better than either static counting on
the non-chordal ones it converged on, and stuck on the rest.  This probe asks
the same question of clustering that was not manufactured: the maximal-clique
region graphs of neighbourhoods taken out of real networks.

Method.  Six networks from Netzschleuder, three whose clustering is generated by
groups -- a paper, a scene, a band each make a clique of their members by
construction -- and three whose clustering is not, being friendship, contact or
a season's schedule.  From each, take every ego-network (a vertex with its
neighbours, induced) of between 8 and 20 vertices whose maximal cliques are not
treelike, subsample to at most ten, and run the same four numbers as
``gbp_cliques.py``: exact ``ln Z`` by enumeration, the Bethe counting, the
Mobius counting on isolated regions, and GBP to a fixed point.  Twenty vertices
is the enumeration ceiling, and it is why neighbourhoods rather than networks.

What it finds.  The group-generated networks are the easy ones and not by a
little: their ego-networks are chordal far more often, because a union of
cliques glued at cut vertices has no long chordless cycle to begin with, so the
region graph is a junction tree and GBP is exact for free.  Where the clustering
is not group-generated the region graph is usually not a junction tree, and
there the honest finding is worse than on hyperbolic graphs: convergence stops
implying accuracy.  A fixed point reached to a residual of 1e-13 can still be
wrong in ``ln Z`` by a quantity of order one.

Networks are fetched through ``graph_tool.collection.ns`` and cached as edge
lists next to the other Netzschleuder dumps the book uses, so a second run needs
neither graph-tool nor a network connection.

    python probe/gbp_real.py
"""

import csv
import io
import json
import sys
import zipfile
from pathlib import Path

import networkx as nx
import numpy as np

sys.path.insert(0, str(Path.home() / 'av2atg' / 'chygraph' / 'src'))

from chygraph_statmech.gbp import (GBP, exact_log_Z, ising_factors,  # noqa: E402
                                   static_log_Z)
from chygraph_statmech.region import RegionGraph, overlap_profile  # noqa: E402

OUT = Path(__file__).parent / 'results' / 'gbp_real.json'
SHARDS = Path(__file__).parent / 'results' / 'gbp_real_parts'
CACHE = (Path.home() / 'av2atg' / 'LocalNetworkGrowth' / 'figs' / 'data'
         / 'netzschleuder')

# (netzschleuder key, label, family).  "grouped" means the clustering is
# generated by groups the data records: an author list, a scene, a band.  Every
# such group is a clique of its members whether or not those members are
# otherwise related, which is the chygraph's own picture of where complexes come
# from.  "dyadic" means the edges were recorded one pair at a time and the
# triangles are whatever homophily or geometry left behind.
NETWORKS = [
    ('netscience',       'Co-authorship',  'grouped'),
    ('lesmis',           'Les Mis. scenes', 'grouped'),
    ('jazz_collab',      'Jazz bands',     'grouped'),
    ('football',         'Football',       'dyadic'),
    ('facebook_friends', 'Facebook',       'dyadic'),
    ('sp_hospital',      'Hospital contacts', 'dyadic'),
]

EGO_MIN, EGO_MAX = 8, 20     # 20 vertices is the exact-enumeration ceiling
PER_NETWORK = 10             # ego-networks kept per network
COUPLINGS = (0.3, 0.8)
DAMPING = (0.5, 0.9, 0.97, 0.995, 0.999)
CONVERGED = 1e-9
SEED = 0


# ------------------------------------------------------------------ loading
def _fetch(key):
    """Edge list of one Netzschleuder network through graph-tool."""
    import graph_tool.all as gt
    g = gt.collection.ns[key]
    g = gt.Graph(gt.GraphView(g, directed=False), prune=True, directed=False)
    gt.remove_self_loops(g)
    gt.remove_parallel_edges(g)
    g = gt.Graph(gt.GraphView(g, vfilt=gt.label_largest_component(g)),
                 prune=True)
    return [(int(e.source()), int(e.target())) for e in g.edges()]


def load(key):
    """The largest component of one network, simple and undirected, cached."""
    stem = key.replace('/', '_')
    path = CACHE / f'{stem}__{stem}.csv.zip'
    if not path.exists():
        edges = _fetch(key)
        CACHE.mkdir(parents=True, exist_ok=True)
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(['# source', 'target'])
        w.writerows(edges)
        with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as z:
            z.writestr('edges.csv', buf.getvalue())
        print(f'  cached {path.name}', flush=True)
    with zipfile.ZipFile(path) as z:
        raw = z.read('edges.csv').decode()
    G = nx.Graph()
    for line in io.StringIO(raw):
        if line.startswith('#') or not line.strip():
            continue
        u, v = line.split(',')[:2]
        u, v = u.strip(), v.strip()
        if u != v:
            G.add_edge(u, v)
    return G


def egonets(G, rng):
    """Non-treelike induced neighbourhoods, subsampled to PER_NETWORK.

    Isomorphic duplicates are dropped.  Two vertices with the same neighbours
    -- two authors on the same one paper, two characters in the same one scene
    -- induce the same ego-network, and counting it twice would let one local
    structure speak with two voices.
    """
    out, seen = [], set()
    for v in sorted(G, key=str):
        ego = sorted([v] + list(G[v]), key=str)
        if not EGO_MIN <= len(ego) <= EGO_MAX:
            continue
        H = nx.convert_node_labels_to_integers(G.subgraph(ego))
        cx = [sorted(c) for c in nx.find_cliques(H)]
        if overlap_profile(cx)['treelike']:
            continue
        cert = nx.weisfeiler_lehman_graph_hash(H, iterations=4)
        if cert in seen:
            continue
        seen.add(cert)
        out.append((v, H))
    if len(out) > PER_NETWORK:
        idx = rng.choice(len(out), PER_NETWORK, replace=False)
        out = [out[i] for i in sorted(idx)]
    return out


# ------------------------------------------------------------------ one run
def run_one(H, bJ):
    """The four numbers, on one ego-network at one coupling."""
    n = H.number_of_nodes()
    cx = [sorted(c) for c in nx.find_cliques(H)]
    prof = overlap_profile(cx)
    rg = RegionGraph(cx, max_rounds=6)
    if not rg.counting_is_valid():
        return None
    edges = sorted({tuple(sorted(e)) for e in H.edges()})
    f = ising_factors(edges, bJ)
    exact = exact_log_Z(f, range(n))
    best = None
    for d in DAMPING:
        g = GBP(rg, f, damping=d).run(8000)
        if best is None or g.residual < best[0].residual:
            best = (g, d)
        if g.residual < CONVERGED:
            break
    g, d = best
    return {
        'n': n, 'm': len(edges), 'beta_J': bJ,
        'n_cliques': len(cx), 'n_regions': len(rg.regions),
        'shared_2plus': prof['shared_2plus'],
        'chordal': bool(nx.is_chordal(H)),
        'exact': exact,
        'bethe': static_log_Z(rg.bethe_counting(), f) - exact,
        'kikuchi': static_log_Z(rg.counting, f) - exact,
        'gbp': g.log_Z() - exact, 'residual': g.residual, 'damping': d,
        'consistency': g.consistency() if np.isfinite(g.residual) else None,
        # with no field the exact <sigma_v> is zero by spin reversal, so this is
        # a direct read-out of whether the fixed point has broken the symmetry
        'mean_abs_m': (float(np.mean(np.abs(list(g.magnetisation().values()))))
                       if np.isfinite(g.residual) else None),
    }


def one_network(key, label, family):
    """Every run for one network.  The seed is the network's position in
    NETWORKS, so a network's sample does not depend on which others were run
    beside it, and running them separately reproduces running them together."""
    G = load(key)
    C = nx.average_clustering(G)   # the $C$ of Chapter 3's table
    rng = np.random.default_rng(SEED + [k for k, _, _ in NETWORKS].index(key))
    eg = egonets(G, rng)
    print(f'{label}: n={G.number_of_nodes()} m={G.number_of_edges()} '
          f'C={C:.3f}, {len(eg)} ego-networks', flush=True)
    rows = []
    for v, H in eg:
        for bJ in COUPLINGS:
            r = run_one(H, bJ)
            if r is None:
                continue
            r.update(network=label, key=key, family=family,
                     clustering=C, ego=str(v))
            rows.append(r)
            print(f"  ego={str(v)[:12]:>12s} n={r['n']:>2d} bJ={bJ} "
                  f"chordal={r['chordal']:d} gbp={r['gbp']:+.2e} "
                  f"res={r['residual']:.0e} kik={r['kikuchi']:+.2e} "
                  f"bethe={r['bethe']:+.2e}", flush=True)
    return rows


def main():
    """`gbp_real.py <key>` runs one network into a shard; no argument merges
    the shards, running any that are missing."""
    SHARDS.mkdir(parents=True, exist_ok=True)
    if len(sys.argv) > 1:
        key = sys.argv[1]
        label, family = next((l, f) for k, l, f in NETWORKS if k == key)
        rows = one_network(key, label, family)
        shard = SHARDS / f'{key.replace("/", "_")}.json'
        json.dump(rows, shard.open('w'), indent=1)
        print('wrote', shard)
        return

    rows = []
    for key, label, family in NETWORKS:
        shard = SHARDS / f'{key.replace("/", "_")}.json'
        if not shard.exists():
            json.dump(one_network(key, label, family), shard.open('w'),
                      indent=1)
        part = json.load(shard.open())
        # recomputed here rather than trusted from the shard, so that a set of
        # shards written at different times still reports one definition of C
        C = nx.average_clustering(load(key))
        for r in part:
            r['clustering'] = C
        rows += part

    json.dump(rows, OUT.open('w'), indent=1)
    summarise(rows)
    print('wrote', OUT)


def summarise(rows):
    print()
    for fam in ('grouped', 'dyadic'):
        sel = [r for r in rows if r['family'] == fam]
        ch = [r for r in sel if r['chordal']]
        nc = [r for r in sel if not r['chordal']]
        conv = [r for r in nc if r['residual'] < CONVERGED]
        print(f'{fam:>8}: {len(sel):>3} runs, {len(ch)} chordal '
              f'({100 * len(ch) / max(len(sel), 1):.0f}%), '
              f'{len(nc)} not, of which {len(conv)} converge')
        if ch:
            print(f'          chordal GBP error at worst '
                  f'{max(abs(r["gbp"]) for r in ch):.1e}')
        if conv:
            g = [abs(r['gbp']) for r in conv]
            k = [abs(r['kikuchi']) for r in conv]
            print(f'          converged non-chordal: GBP {min(g):.1e} to '
                  f'{max(g):.1e}, Mobius {min(k):.1e} to {max(k):.1e}')


if __name__ == '__main__':
    main()
