[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "statmech"
version = "0.0.1"
description = "Statistical mechanics on chygraphs: Bethe-Peierls beyond graphs"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = [
    "sympy",
    "percolation",
    "numpy",
    "scipy",
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
"Vazquez & Weigt 2003" = "https://arxiv.org/abs/cond-mat/0207035"
"Repository" = "https://github.com/av2atgh/chygraph"

[tool.setuptools.packages.find]
where = ["src"]
