"""Chapter 11: vertex cover, leaf removal and core percolation.

  fig-core     the leaf-removal core against chy-degree, for complexes of
               cardinality two, three and four: a transition at <k> = e in the
               first case and no transition at all in the others
  fig-hrg-c    the empirical payoff. Core of hyperbolic random graphs against
               their clustering, with the chygraph prediction evaluated on the
               measured clique ensemble.  `figure_hrg` is the same three
               quantities against mean degree, log-log and with the
               degree-matched control; it was Fig. 11.4 and is no longer in the
               text, so it is not generated by __main__ any more
  fig-vw       the transition degree correlations do produce. Minimal cover
               size and the stability of the map that gives it, along the
               assortativity axis of VW03 Eq. (18), at frozen degree
               distribution

Chapter 11's first figure, leaf removal frame by frame, is TikZ in `cover.tex`.

The hyperbolic-graph points are read from `../probe/results/prediction4.csv`,
the cached output of `../probe/prediction4.py`; that script builds the graphs,
runs leaf removal on them and measures the clique ensemble, none of which the
book recomputes.
"""

import sys
from pathlib import Path

import numpy as np
from scipy.special import lambertw
from sympy import exp as sexp

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / 'percolation' / 'src'))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / 'statmech' / 'src'))
import statmech.hittingset as hs  # noqa: E402
from statmech import core as co  # noqa: E402
from statmech import cover as cv  # noqa: E402
from statmech import vertexcover as vc  # noqa: E402

OUT = Path(__file__).resolve().parent
PROBE = Path(__file__).resolve().parents[2] / 'statmech' / 'probe' / 'results'
DARK, MID, LIGHT = '0.10', '0.45', '0.70'


def _mpl():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    return plt


def _tidy(ax):
    ax.tick_params(labelsize=8)
    for sp in ('top', 'right'):
        ax.spines[sp].set_visible(False)


# ------------------------------------------------------------ (1) one point
def check_threshold():
    """<k> = e, reached from core percolation and from Chapter 10's map."""
    t = co.core_threshold(lambda k: co.graph(mean=k))
    assert abs(t - np.e) < 1e-9, t
    khs = hs.rsb_point([2], [1.0])
    print(f'  core-percolation threshold   <k> = {t:.10f}')
    print(f'  hard-field instability       <k> = {khs:.10f}')
    print(f'  e                            <k> = {np.e:.10f}')
    print(f'  the three agree to {abs(t - khs):.1e}: one point, computed twice')


# ---------------------------------------------- (2) the induced-graph cover
def check_induced_cover():
    """Vertex cover of the induced graph: same family, tighter constraint."""
    print('     <k>   Weigt-Hartmann   induced cover   hitting set')
    for k in (1.0, 2.0, 2.5):
        W = float(np.real(lambertw(k)))
        wh = 1 - (2 * W + W**2) / (2 * k)
        a = cv.poisson([2], [k]).cover_size()
        b = hs.poisson([2], [k]).cover_size()
        assert abs(a - wh) < 1e-9 and abs(b - wh) < 1e-9
        print(f'  {k:>6.1f}   {wh:>14.6f}   {a:>13.6f}   {b:>11.6f}')
    print('    the two problems coincide at cardinality two, as they must')
    x = hs.layer_symbols(1)
    tri = cv.CliqueCover([3], x[0]).cover_size()
    assert abs(tri - 0.5) < 1e-12
    print(f'  isolated triangles: hard field {tri:.4f}, truth {2/3:.4f}')
    print('    the mirror of Sec. 10.3 -- same defect, different problem, and')
    print('    the same wrong answer 1/2')


# ------------------------------------------- (3) no core-free branch above c=2
def check_core_free():
    """A layer of cardinality three or more removes the core-free branch."""
    for c in (2, 3, 4, 5, 8):
        free = co.clique_network(c, 1.0).has_core_free_branch()
        assert free == (c == 2), c
        print(f'  c = {c}: core-free branch {"exists" if free else "does not exist"}')
    # and then the core is exactly the non-isolated fraction
    print('  for a pure clique network of cardinality >= 3 the core is'
          ' 1 - e^{-<k>}:')
    for c in (3, 4, 6):
        for k in (0.3, 1.0, 2.5):
            got = co.clique_network(c, k).core_fraction()
            assert abs(got - (1 - np.exp(-k))) < 1e-9, (c, k)
        print(f'    c = {c}: every non-isolated vertex is core   OK')


def check_factorisation():
    """The factorisation that kills the core-free branch, symbolically."""
    from sympy import Symbol, expand, factor, simplify, symbols
    d = Symbol('delta')
    for c in range(2, 10):
        f = (c - 1) * d**(c - 2) - (c - 2) * d**(c - 1) - 1
        g = -(1 - d)**2 * sum((j + 1) * d**j for j in range(c - 2))
        assert simplify(expand(f - g)) == 0, c
    print('  f(delta) = -(1-delta)^2 sum_{j<c-2} (j+1) delta^j, '
          'for c = 2 ... 9   OK')
    print('    at c = 2 the sum is empty and f == 0: the condition is an '
          'identity')
    print('    at c >= 3 every coefficient is positive, so the only root is '
          'delta = 1')


def check_against_leaf_removal():
    """Eq. (11.4) against pure leaf removal on graphs built to match it."""
    path = PROBE / 'validate_core.txt'
    rows = []
    for line in path.read_text().splitlines()[2:]:
        f = line.split()
        if len(f) == 6:
            rows.append((int(f[0]), float(f[4]), float(f[5])))
    err = [e for _, sim, e in rows if sim > 1e-3]
    print(f'  {len(rows)} ensembles at n = 4e5, cardinalities '
          f'{sorted({c for c, _, _ in rows})}:')
    print(f'    error against pure leaf removal runs {min(err):.1e} to '
          f'{max(err):.1e}')
    print(f'    (from {path.name}, the cached output of probe/validate_core.py)')


def check_core_can_be_tiny():
    """The strong reading is false: the core need not be large."""
    x = hs.layer_symbols(2)
    for kL, kT in ((1.0, 1e-2), (1.0, 1e-3), (1.0, 1e-4)):
        phi = sexp(kL * (x[0] - 1)) * sexp(kT * (x[1] - 1))
        f = co.CorePercolation([2, 3], phi).core_fraction()
        print(f'  links <k> = {kL:g}, triangles <k> = {kT:g}:  core = {f:.3e}')
    print('    the algebra forbids a core-free branch; it does not make the'
          ' core big')


def figure_core():
    plt = _mpl()
    fig, ax = plt.subplots(figsize=(4.3, 2.6))
    ks = np.linspace(0.05, 6.0, 120)
    # c = 3 and c = 4 fall exactly on top of each other, which is the point;
    # they are drawn in different styles so that both are visible.
    for c, col, style, kw in ((2, DARK, '-', {}), (3, MID, '-', {}),
                              (4, LIGHT, '--', {'dashes': (4, 2)})):
        ax.plot(ks, [co.clique_network(c, k).core_fraction() for k in ks],
                style, lw=1.6, color=col, label=f'$c={c}$', **kw)
    ax.axvline(np.e, ls=':', lw=0.9, color=DARK)
    ax.annotate(r'$\langle k\rangle=e$', xy=(np.e + 0.13, 0.06), fontsize=7.5,
                color='0.3')
    ax.annotate(r'$1-e^{-\langle k\rangle}$: $c=3$ and $4$ coincide',
                xy=(1.55, 0.86), fontsize=7, color='0.35')
    ax.set_xlabel(r'chy-degree $\langle k\rangle$', fontsize=8.5)
    ax.set_ylabel(r'$P_C(\mathrm{VC},\,\chi)$', fontsize=9)
    ax.set_ylim(-0.02, 1.02)
    ax.legend(frameon=False, fontsize=8, loc='center right')
    _tidy(ax)
    fig.tight_layout()
    fig.savefig(OUT / 'fig-core.pdf')
    print(f'  wrote {OUT / "fig-core.pdf"}')


# ------------------------------------------------ (4) hyperbolic random graphs
def _hrg():
    import csv
    rows = []
    with open(PROBE / 'prediction4.csv') as fh:
        for r in csv.DictReader(fh):
            rows.append({k: (float(v) if k != 'seed' else int(v))
                         for k, v in r.items()})
    return rows


def _fit(k, y, kmax=1.0):
    """Power-law exponent of y ~ k^theta, fitted on k <= kmax."""
    k, y = np.asarray(k), np.asarray(y)
    m = (k <= kmax) & (y > 0)
    return float(np.polyfit(np.log(k[m]), np.log(y[m]), 1)[0])


def check_hrg():
    rows = _hrg()
    print('    tau   theta measured   theta chygraph   control')
    for tau in (2.5, 2.9, 2.1):
        r = [x for x in rows if abs(x['tau'] - tau) < 1e-9]
        k = [x['kbar'] for x in r]
        tm = _fit(k, [x['hrg_measured'] for x in r])
        tc = _fit(k, [x['hrg_chygraph'] for x in r])
        ctrl = max(x['cfg_measured'] for x in r if x['kbar'] <= 1.0)
        print(f'  {tau:>5.1f}   {tm:>13.3f}   {tc:>14.3f}   '
              f'{"no core" if ctrl <= 0 else f"{ctrl:.2e}"}')
    print('    the predicted exponent barely moves with tau; the measured one'
          ' does')
    # the one place the control does have a core
    r = [x for x in rows if abs(x['tau'] - 2.9) < 1e-9 and x['kbar'] > 5]
    cp = np.mean([x['cfg_chygraph'] for x in r])
    cm = np.mean([x['cfg_measured'] for x in r])
    print(f'  the control at tau = 2.9, <k> = 6 does have a core: predicted '
          f'{cp:.3f},\n    measured {cm:.3f} -- agreement to '
          f'{100*abs(cp-cm)/cm:.0f} per cent, same map, same pipeline')
    # how much of the real core the chygraph accounts for
    fr = [x['hrg_chygraph'] / x['hrg_measured'] for x in rows
          if x['hrg_measured'] > 0 and abs(x['tau'] - 2.9) < 1e-9]
    print(f'  fraction of the measured core accounted for at tau = 2.9: '
          f'{min(fr):.2f} to {max(fr):.2f}')


def figure_hrg():
    plt = _mpl()
    rows = _hrg()
    fig, axes = plt.subplots(1, 2, figsize=(4.6, 2.5), sharey=True)
    for ax, tau in zip(axes, (2.5, 2.9)):
        r = sorted((x for x in rows if abs(x['tau'] - tau) < 1e-9),
                   key=lambda z: z['kbar'])
        k = np.array([x['kbar'] for x in r])
        ax.loglog(k, [x['hrg_measured'] for x in r], 'o', ms=3.4, color=DARK,
                  label='measured')
        ax.loglog(k, [x['hrg_chygraph'] for x in r], 's', ms=3.4, mfc='white',
                  mew=0.9, color=DARK, label='LCZP')
        ctrl = np.array([x['cfg_measured'] for x in r])
        floor = 3e-6
        ax.loglog(k, np.where(ctrl > 0, ctrl, floor), '^', ms=3.2,
                  color=LIGHT, label='degree-matched')
        th = _fit(k, [x['hrg_chygraph'] for x in r])
        kk = np.array([k.min(), 1.0])
        c0 = r[0]['hrg_chygraph'] / k.min()**th
        ax.loglog(kk, c0 * kk**th, '-', lw=0.9, color='0.55')
        ax.set_title(rf'$\tau={tau}$', fontsize=8.5)
        ax.set_xlabel(r'mean degree $\langle k\rangle$', fontsize=8.5)
        ax.set_ylim(1e-6, 2.0)
        _tidy(ax)
    axes[0].set_ylabel('core fraction', fontsize=8.5)
    axes[0].legend(frameon=False, fontsize=6.6, loc='upper left')
    axes[1].annotate('control has no core here', xy=(0.055, 6e-6),
                     fontsize=6.2, color='0.45')
    fig.tight_layout()
    fig.savefig(OUT / 'fig-hrg.pdf')
    print(f'  wrote {OUT / "fig-hrg.pdf"}')



def table_real_core():
    """Table 11.2: leaf removal on sixteen real networks, measured against
    predicted.

    Reads probe/results/real_core.json -- the measured core and the Eq. (11.4)
    prediction on the maximal-clique ensemble of that same graph.  The cache
    also holds a degree-matched rewiring, which the section no longer uses:
    its clustering is zero by construction, so it separates nothing that mean
    degree does not already separate, and it was a third number to carry.
    Sorted by mean degree, which is what drives the split: seven of the sixteen
    are more than half core, and on those a method that returns "nearly all of
    it" agrees for free.  Mean degree alone does not make the cut, though --
    the Figeys interactome is at <k> = 5.8 with no core at all -- so the
    criterion used is the measured core itself.
    """
    import json
    rows = json.loads((PROBE / 'real_core.json').read_text())
    rows.sort(key=lambda r: r['kbar'])
    out = [r'\begin{tabular}{lrrrr}', r'\hline\hline',
           r' & & & \multicolumn{2}{c}{core fraction '
           r'$P_{C}(\mathrm{VC},\cdot)$}\\',
           r'network & $\ave{k}$ & $C$ & leaf removal & LCZP\\',
           r' & & & on the graph & on its cliques\\',
           r'\hline']
    for r in rows:
        out.append(f"{r['label']} & {r['kbar']:.2f} & {r['C']:.3f} & "
                   f"{r['measured']:.4f} & {r['chygraph']:.4f}\\\\")
    out += [r'\hline\hline', r'\end{tabular}']
    (OUT / 'tab-real-core.tex').write_text('\n'.join(out) + '\n')
    print('  wrote tab-real-core.tex')

    MOSTLY = 0.5                      # more than half the graph is core
    rest = [r for r in rows if r['measured'] < MOSTLY]
    car = [r for r in rest if r['measured'] > 0.02]
    print(f'  {len(car)} networks that carry the comparison, '
          f'and the prediction on them:')
    for r in car:
        print(f"     {r['label']:18s} <k>={r['kbar']:5.2f}  C={r['C']:.3f}  "
              f"measured={r['measured']:.4f}  chygraph={r['chygraph']:.4f} "
              f"({100*r['recovered']:4.1f}%)")
    zero = [r for r in rows if r['measured'] == 0.0]
    print(f"  {len(zero)} with no measured core at all; chygraph predicts "
          f"{min(r['chygraph'] for r in zero):.4f} to "
          f"{max(r['chygraph'] for r in zero):.4f}")
    most = [r for r in rows if r['measured'] >= MOSTLY]
    print(f'  {len(most)} more than half core ('
          f'{min(r["measured"] for r in most):.2f} to '
          f'{max(r["measured"] for r in most):.2f}), at <k> '
          f'{min(r["kbar"] for r in most):.1f} to '
          f'{max(r["kbar"] for r in most):.1f} and C >= '
          f'{min(r["C"] for r in most):.2f}: nothing is distinguished there')


def figure_real_core():
    """Table 11.2 as a picture: core against clustering, sixteen real networks.

    Both of the table's core columns -- leaf removal on the graph, and the LCZP
    map on that graph's own maximal cliques -- against its clustering column.
    The shading is not a third measurement: it marks the seven networks that are
    more than half core already, where a method returning "nearly all of it"
    agrees for free.  They are the seven densest but one, and the cut is taken
    on the measured core rather than on <k> because <k> mis-sorts one network
    -- Figeys, at 5.8, has no core.
    """
    import json
    plt = _mpl()
    rows = json.loads((PROBE / 'real_core.json').read_text())
    rows.sort(key=lambda r: r['C'])
    MOSTLY = 0.5
    fig, ax = plt.subplots(figsize=(4.6, 2.8))
    edge = min(r['C'] for r in rows if r['measured'] >= MOSTLY)
    ax.axvspan(edge, 1.0, color='0.92', lw=0, zorder=0)
    C = [r['C'] for r in rows]
    ax.plot(C, [r['measured'] for r in rows], 'o', ms=4.0, color=DARK,
            label='leaf removal')
    ax.plot(C, [r['chygraph'] for r in rows], 's', ms=4.0, mfc='white',
            mew=0.9, color=DARK, label='LCZP on its cliques')
    ax.set_xlabel('clustering coefficient $C$', fontsize=8.5)
    ax.set_ylabel(r'core $P_{C}(\mathrm{VC},\mathrm{G})$', fontsize=8.5)
    ax.set_xlim(-0.03, 0.80)
    ax.set_ylim(-0.04, 1.08)
    _tidy(ax)
    ax.legend(frameon=False, fontsize=7.0, loc='upper left')
    ax.annotate('almost everything is core here\nwhatever the structure',
                xy=(0.785, 0.055), fontsize=6.2, color='0.45', ha='right',
                va='bottom')
    fig.tight_layout()
    fig.savefig(OUT / 'fig-real-core.pdf')
    print(f'  wrote {OUT / "fig-real-core.pdf"}')
    lo = [r for r in rows if r['measured'] < MOSTLY]
    print(f'  shading starts at C = {edge:.2f}; {len(rows) - len(lo)} networks '
          f'in it, every one more than half core')
    z = [r for r in lo if r['measured'] == 0.0]
    print(f'  of the other {len(lo)}, {len(z)} have no core and none is '
          f'predicted (max {max(r["chygraph"] for r in z):.4f})')


def check_vc_instability():
    """Eq. (11.10): the cover map's own hard-field instability at cardinality c.

    Eliminating kappa between the Poisson fixed point sigma = exp(k(u^{c-1}-1)),
    u = 1 - sigma, and |F'| = k(c-1) sigma u^{c-2} = 1 leaves one transcendental
    equation in sigma, and <k>_c = 1/(sigma u^{c-2}) is the induced mean degree
    there.  Checked by evaluating |F'| at the root the closed form gives.
    """
    from scipy.optimize import brentq
    print('   c    sigma*        <k>_c        |F\'| at that point')
    for c in range(2, 11):
        f = lambda x: np.log(x) - ((1 - x)**(c - 1) - 1) / ((c - 1) * x * (1 - x)**(c - 2))
        sig = brentq(f, 1e-9, 1 - 1e-9, xtol=1e-15)
        k = 1.0 / (sig * (1 - sig)**(c - 2))
        m = cv.CliqueCover([c], hs.poisson_phi([k / (c - 1)]))
        s = m.solve()
        slope = (k / (c - 1)) * (c - 1) * s[0] * (1 - s[0])**(c - 2)
        assert abs(slope - 1.0) < 1e-9, (c, slope)
        print(f'  {c:2d}   {sig:.10f}  {k:.10f}   {slope:.10f}')
    assert abs(1.0 / (0.3678794411714423 * 1.0) - np.e) < 1e-9
    print('    e at c = 2, then 4.7836, 7.0871, 9.5736; Eq. (10.4) does not move')


def check_small_core():
    """Eq. (11.9): the core is linear in the clique chy-degree, with that slope.

    core ~ kappa_c psi0 [1 - d^{c-1} - (c-1) psi0 d^{c-2}], d = 1 - psi0, with
    psi0 the link layer's own leaf-ready probability.  The bracket is
    1 - zeta - xi on the link background and vanishes identically at c = 2.
    """
    from scipy.optimize import brentq
    print('   <k>  c    numeric/eps     formula      rel')
    for k in (0.5, 1.0, 2.0):
        p0 = brentq(lambda p: np.exp(-k * p) - p, 1e-12, 1.0, xtol=1e-15)
        d = 1 - p0
        for c in (3, 4, 5, 8):
            pred = p0 * (1 - d**(c - 1) - (c - 1) * p0 * d**(c - 2))
            num = co.CorePercolation([2, c],
                                     hs.poisson_phi([k, 1e-5])).core_fraction() / 1e-5
            rel = abs(num - pred) / pred
            assert rel < 1e-3, (k, c, num, pred)
            print(f'  {k:4} {c:2d}   {num:.8f}   {pred:.8f}   {rel:.1e}')
        assert abs(p0 * (1 - d - 1 * p0 * 1)) < 1e-12      # c = 2 vanishes
    p0 = brentq(lambda p: np.exp(-p) - p, 1e-12, 1.0, xtol=1e-15)
    print(f'    at <k> = 1, kappa_tri = 1e-3: {1e-3 * p0**3:.6e}, '
          "Sec. 11.5's 1.8e-4")


# ----------------------------------------- (5) the five structures of Fig. 2.5
FIVE = [
    ('A graph',                 [2]),
    ('A hypergraph',            [3]),
    ('A multiplex network',     [2, 2]),
    ('Interacting graphs',      [2, 2, 2]),
    ('Interacting hypergraphs', [3, 3, 3]),
    ('A clustered graph',       [2, 3]),
]


def _split(cards, kbar):
    """Layer chy-degrees splitting an induced mean degree ``kbar`` evenly.

    A layer-``l`` complex supplies ``c_l - 1`` neighbours per member, so the
    induced mean degree is ``sum_l kappa_l (c_l - 1)``.  Holding that fixed is
    what makes the six rows comparable: they are the same graph density
    arranged into different complexes.
    """
    return [kbar / len(cards) / (c - 1) for c in cards]


# ------------------------------------------- (6) the correlated-graph transition
VW_TAUS = (2.5, 3.0)
VW_DMAX = 800


def _vw_lambda(r, e, q, pi):
    """|leading eigenvalue| of the Jacobian, from the secular equation.

    ``J = -r diag(a) - (1-r) 1 (q a)^T`` with ``a_d = d (1-pi_d)^{d-1}`` is
    diagonal plus rank one, so with ``mu = -lambda`` its leading eigenvalue is
    the unique root of ``(1-r) sum_d q_d a_d / (mu - r a_d) = 1`` above
    ``r max(a)``.  No eigensolve, and ``vertexcover.is_unstable`` is the same
    statement evaluated at ``mu = 1``.
    """
    from scipy.optimize import brentq
    a = vc.jacobian_spectrum(r, e, q, pi)
    lo = r * a.max() + 1e-12
    g = lambda mu: (1 - r) * (q * a / (mu - r * a)).sum() - 1.0
    hi = max(lo * 2, 4.0)
    while g(hi) > 0:
        hi *= 2
    return brentq(g, lo, hi, xtol=1e-13) if g(lo) > 0 else lo


def _vw(tau, dmax=VW_DMAX, n=61):
    """x_c(r) and the leading |eigenvalue| along VW03 Eq. (18), at fixed p_d.

    The map is anti-monotone, so its fixed point is reached by bisection on the
    one scalar the correlation model closes on rather than by iteration, and
    stability is then asked of the Jacobian there.  That is what lets the curve
    be drawn past r_c at all: VW03's own instrument -- the iteration failing to
    converge -- cannot report a fixed point it never reaches.
    """
    p = vc.scale_free(tau, dmax)
    e, q, _ = vc.excess(p)
    r = np.linspace(0.0, 1.0, n)
    x = np.empty(n)
    lam = np.empty(n)
    for i, ri in enumerate(r):
        pi = vc.solve(ri, e, q)
        x[i] = vc.cover_size(p, pi)
        lam[i] = _vw_lambda(ri, e, q, pi)
    return r, x, lam, vc.rsb_point(tau, dmax)


def check_vw():
    """Sec. 11.8: the uncorrelated corner, and where replica symmetry breaks."""
    for k in (1.0, 2.0, 3.0, 5.0, 10.0):
        p = vc.poisson(k, 4000)
        e, q, _ = vc.excess(p)
        W = float(np.real(lambertw(k)))
        wh = 1 - (2 * W + W**2) / (2 * k)
        x = vc.cover_size(p, vc.solve(0.0, e, q))
        assert abs(x - wh) < 1e-12, (k, x, wh)
    print('  Eq. (11.12) at e_dd\' = q_d q_d\' returns Weigt-Hartmann to 1e-12')
    print('    at <k> = 1, 2, 3, 5, 10')

    def unstable(k):                       # the uncorrelated Poisson corner
        p = vc.poisson(k, 4000)
        e, q, _ = vc.excess(p)
        return vc.is_unstable(0.0, e, q, vc.solve(0.0, e, q))
    lo, hi = 1.0, 5.0
    for _ in range(60):
        m = 0.5 * (lo + hi)
        lo, hi = (lo, m) if unstable(m) else (m, hi)
    kc = 0.5 * (lo + hi)
    assert abs(kc - np.e) < 1e-12, kc
    print(f'  its instability there   <k> = {kc:.12f}')
    print(f'  e                       <k> = {np.e:.12f}')
    print('    a third route to Sec. 11.4\'s number, on a different code path')

    p = vc.scale_free(2.5, 200)                 # secular root vs dense eigensolve
    e, q, _ = vc.excess(p)
    d = max(abs(_vw_lambda(ri, e, q, vc.solve(ri, e, q))
                - abs(vc.leading_eigenvalue(ri, e, q, vc.solve(ri, e, q))))
            for ri in (0.2, 0.5, 0.8))
    assert d < 1e-9, d
    print(f'  secular root agrees with a dense eigensolve to {d:.1e}')

    for tau in VW_TAUS:
        r, x, lam, rc = _vw(tau, n=11)
        i = int(np.argmin(np.abs(r - 0.7)))
        print(f'  tau = {tau}: r_c = {rc:.4f}, '
              f'x_c from {x[0]:.4f} at r = 0 to {x[i]:.4f} at r = {r[i]:.1f} '
              f'({100*(x[i]/x[0]-1):.0f} per cent)')
    print('  the heavier tail breaks first, and p_d has not moved')


def _vw_core():
    """Measured leaf-removal core on graphs drawn from the ensemble.

    probe/results/vw_core.json, the cached output of probe/vw_core.py: pure
    leaf removal run on graphs wired by VW03's own generator, nothing fitted
    and no chygraph involved.
    """
    import json
    return json.loads((PROBE / 'vw_core.json').read_text())


def figure_vw():
    plt = _mpl()
    fig = plt.figure(figsize=(4.8, 4.5))
    gs = fig.add_gridspec(2, 2, height_ratios=(1.0, 0.88), hspace=0.42,
                          wspace=0.36)
    axes = [fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[0, 1])]
    axc = fig.add_subplot(gs[1, :])
    styles = {2.5: (MID, 'o', (0, (3, 1.4))), 3.0: (DARK, 's', (0, (1.4, 1.2)))}
    rows = _vw_core()
    for tau in VW_TAUS:
        col, mk, dash = styles[tau]
        r, x, lam, rc = _vw(tau)
        rs, br = r <= rc, r >= rc
        axes[0].plot(r[rs], x[rs], '-', lw=1.2, color=col, label=rf'$\tau={tau}$')
        axes[0].plot(r[br], x[br], ls=dash, lw=1.0, color=col)
        axes[1].plot(r[rs], lam[rs], '-', lw=1.2, color=col)
        axes[1].plot(r[br], lam[br], ls=dash, lw=1.0, color=col)
        for ax, y in ((axes[0], np.interp(rc, r, x)), (axes[1], 1.0)):
            ax.plot([rc], [y], mk, ms=4.0, mfc='white', mew=1.0, color=col)
        d = sorted((z for z in rows if abs(z['tau'] - tau) < 1e-9),
                   key=lambda z: z['r'])
        rr = np.array([z['r'] for z in d])
        axc.errorbar(rr, [z['core'] for z in d], [z['core_sd'] for z in d],
                     fmt=mk, ms=3.2, lw=0, elinewidth=0.7, capsize=1.4,
                     mfc='white', mew=0.9, color=col, label=rf'$\tau={tau}$')
        axc.axvline(rc, lw=0.7, ls=(0, (2, 1.6)), color=col, zorder=0)
    axes[1].axhline(1.0, lw=0.7, color='0.6', zorder=0)
    axes[0].set_ylabel('minimal cover size $x_{c}$', fontsize=8.5)
    axes[1].set_ylabel(r'$|\lambda|$ of the Jacobian', fontsize=8.5)
    axes[1].set_ylim(0.0, 1.8)
    axc.set_ylabel(r'core $P_{C}(\mathrm{VC},\mathrm{G})$', fontsize=8.5)
    axc.set_ylim(-0.014, 0.34)
    for ax in list(axes) + [axc]:
        ax.set_xlabel('assortativity $r$', fontsize=8.5)
        ax.set_xlim(-0.02, 1.02)
        _tidy(ax)
    axes[0].legend(frameon=False, fontsize=7.2, loc='upper left')
    axes[0].annotate('RS broken: a fixed\npoint, not an answer',
                     xy=(0.94, 0.4985), xytext=(0.70, 0.400), fontsize=6.2,
                     color='0.45', ha='center', va='top',
                     arrowprops=dict(arrowstyle='-', lw=0.6, color='0.6',
                                     shrinkA=3, shrinkB=2))
    axes[1].annotate(r'$|\lambda|=1$', xy=(0.035, 1.06), fontsize=6.6,
                     color='0.45')
    assert rows[0]['n'] == 200000, rows[0]['n']      # the legend says so
    axc.legend(frameon=False, fontsize=7.2, loc='upper left',
               title=rf'leaf removal, $n=2\times10^{{5}}$',
               title_fontsize=6.6)
    axc.annotate(r'dashed: $r_{\mathrm{c}}$ from the panels above',
                 xy=(0.99, 0.97), xycoords='axes fraction', fontsize=6.2,
                 color='0.45', ha='right', va='top')
    axc.annotate('no core: leaf removal certifies a minimum cover',
                 xy=(0.03, 0.115), xycoords='axes fraction', fontsize=6.2,
                 color='0.45', ha='left', va='bottom')
    fig.savefig(OUT / 'fig-vw.pdf', bbox_inches='tight')
    print(f'  wrote {OUT / "fig-vw.pdf"}')


def figure_vw_t():
    """The measured core of Fig. 11.5's lower panel, against transitivity.

    r is the knob; T is what the ensemble turns out to *be* when the knob is at
    r, measured on the same graphs.  Plotting against it asks whether the two
    tails, which lose replica symmetry at different r, lose it at the same
    amount of structure.  The verticals are T at r_c, carried across by the
    measured and monotone T(r).  Note that T is an outcome and not a control,
    and probe/vw_clustering shows it is only weakly n-independent at tau = 3.0,
    so the axis is not a clean thermodynamic one.
    """
    plt = _mpl()
    fig, ax = plt.subplots(figsize=(4.6, 2.8))
    styles = {2.5: (MID, 'o'), 3.0: (DARK, 's')}
    rows = _vw_core()
    tc = {}
    for tau in VW_TAUS:
        col, mk = styles[tau]
        d = sorted((z for z in rows if abs(z['tau'] - tau) < 1e-9),
                   key=lambda z: z['r'])
        rm = np.array([z['r'] for z in d])
        tm = np.array([z['trans'] for z in d])
        tc[tau] = float(np.interp(vc.rsb_point(tau, VW_DMAX), rm, tm))
        ax.errorbar(tm, [z['core'] for z in d], [z['core_sd'] for z in d],
                    [z['trans_sd'] for z in d], fmt=mk, ms=3.6, lw=0,
                    elinewidth=0.7, capsize=1.4, mfc='white', mew=0.9,
                    color=col, label=rf'$\tau={tau}$')
        ax.axvline(tc[tau], lw=0.7, ls=(0, (2, 1.6)), color=col, zorder=0)
    ax.set_xlabel('transitivity $T$', fontsize=8.5)
    ax.set_ylabel(r'core $P_{C}(\mathrm{VC},\mathrm{G})$', fontsize=8.5)
    ax.set_xlim(-0.004, max(z['trans'] for z in rows) * 1.04)
    ax.set_ylim(-0.014, 0.30)
    _tidy(ax)
    assert rows[0]['n'] == 200000, rows[0]['n']      # the legend says so
    ax.legend(frameon=False, fontsize=7.2, loc='upper left',
              title=r'leaf removal, $n=2\times10^{5}$', title_fontsize=6.6)
    ax.annotate(r'dashed: $T$ at $r_{\mathrm{c}}$', xy=(0.99, 0.97),
                xycoords='axes fraction', fontsize=6.2, color='0.45',
                ha='right', va='top')
    fig.tight_layout()
    fig.savefig(OUT / 'fig-vw-t.pdf')
    print(f'  wrote {OUT / "fig-vw-t.pdf"}')
    print('  T at r_c: ' + ', '.join(f'tau={t} -> {v:.4f}'
                                     for t, v in tc.items()))


def table_five_structures(kbar=2.0):
    """Table 11.1: Chapter 11's three methods on the structures of Fig. 2.5.

    Everything is evaluated at one induced mean degree, below the graph's own
    threshold, because that is where the structures disagree: the all-c=2 rows
    have no core and a certified cover there, and the others do not.
    """
    out = [r'\begin{tabular}{lccrrc}', r'\hline\hline',
           r'structure & $c$ & threshold & $P_{C}$ & cover & certified\\',
           r'\hline']
    print(f'  at induced mean degree <k> = {kbar}')
    rows = []
    for label, cards in FIVE:
        kap = _split(cards, kbar)
        core = co.CorePercolation(cards, hs.poisson_phi(kap))
        cover = cv.CliqueCover(cards, hs.poisson_phi(kap))
        sigma = cover.solve()
        free = core.has_core_free_branch()
        thr = r'$\ave{k}=e$' if free else 'none'
        pc, cs = core.core_fraction(), cover.cover_size(sigma)
        lo, hi = cover.cover_bracket(sigma)
        cert = 'yes' if cover.certified() else 'no'
        assert free == cover.certified()
        if all(c >= 3 for c in cards):        # leaf removal never fires
            assert abs(pc - (1 - np.exp(-sum(kap)))) < 1e-9, (label, pc)
        rows.append((pc, cs))
        cs_txt = f'{cs:.4f}' if free else f'{cs:.4f}$^{{*}}$'
        out.append(f"{label} & ${','.join(map(str, cards))}$ & {thr} & "
                   f"{pc:.4f} & {cs_txt} & {cert}\\\\")
        print(f'    {label:24s} c={str(cards):12s} core={pc:.4f} '
              f'cover={cs:.4f} [{lo:.4f},{hi:.4f}] certified={cert}')
    out += [r'\hline\hline', r'\end{tabular}']
    (OUT / 'tab-five-structures.tex').write_text('\n'.join(out) + '\n')
    two = [r for (label, cards), r in zip(FIVE, rows) if all(c == 2 for c in cards)]
    assert max(abs(a - b) for a, b in zip(two[0], two[1])) < 1e-9
    assert max(abs(a - b) for a, b in zip(two[0], two[2])) < 1e-9
    print(f'  the {len(two)} cardinality-two rows agree: layering does not move the point')
    print('  the pure-clique rows are 1 - Phi(0), every non-isolated vertex')
    print('  wrote tab-five-structures.tex')


if __name__ == '__main__':
    print('one point, three names:')
    check_threshold()
    print('vertex cover of the induced graph:')
    check_induced_cover()
    print('above cardinality two:')
    check_core_free()
    check_factorisation()
    check_core_can_be_tiny()
    check_small_core()
    check_vc_instability()
    print('against pure leaf removal:')
    check_against_leaf_removal()
    print('hyperbolic random graphs:')
    check_hrg()
    print('graphs with degree correlations:')
    check_vw()
    print('the five structures of Fig. 2.5:')
    table_five_structures()
    print('figures:')
    figure_core()
    figure_hrg_c()          # figure_hrg() is Fig. 11.4, removed from the text
    figure_real_core()
    figure_vw()
    figure_vw_t()
